### PR TITLE
Crypto cleanup

### PR DESCRIPTION
**Pull request by lwvmobile**

### CODE REVIEW

**Comment by sp5wwp** [comment]
Would be nice to add AES key loading from file if the string immediately after `-K` contains a dot. For `-k` there's no need for that, as the scrambler key is really short.

**Comment by sp5wwp** [comment]
Thanks for updating the `crypto` branch :)

**Comment by lwvmobile** [comment]
> Would be nice to add AES key loading from file if the string immediately after `-K` contains a dot. For `-k` there's no need for that, as the scrambler key is really short.

I'll see what I can do about reading it in from a file, working on converting tinier-aes to have a .h file and trying to figure out how to update a submodule commit version.

**Comment by sp5wwp** [comment]
Cool! In the meantime, I'm pushing some changes into the `auth` branch.

**Pull request merged**
